# Generated by Django 3.2 on 2021-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
    ]
