# Generated by Django 3.2 on 2021-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='just-a-slug', max_length=255),
            preserve_default=False,
        ),
    ]
