# Generated by Django 3.2 on 2021-04-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
