# Generated by Django 3.2 on 2021-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210417_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10, null=True)),
                ('role_choice', models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Program Director', 'Program Director'), ('Manager', 'Manager'), ('Member', 'Member')], max_length=20, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('bio_pic', models.ImageField(blank=True, null=True, upload_to='uploads/people/')),
                ('bio', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
