# Generated by Django 3.2 on 2021-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto generated from image', null=True, upload_to='uploads/blogs/thumbnails'),
        ),
    ]
