# Generated by Django 3.2 on 2021-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image. Thumbnail will be autogenerated', null=True, upload_to='uploads/blogs/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto generated from image. DO NOT UPLOAD THIS', null=True, upload_to='uploads/blogs/thumbnails'),
        ),
    ]
